Merge the duplicate functions
hust-open-atom-club/linux-edu-rank pull request #24
Opened 2024-10-22 09:37 UTC by Zzzwj666

Merge the duplicate functions is_university_domain and get_university into a new function find_university

2024-10-22 09:45 UTC, Zzzwj666 commented
把原来的两个函数删了又重新commit了一次

2024-10-22 10:14 UTC, mudongliang commented
已指定reviewers，请等待reviewer反馈

2024-10-22 10:56 UTC, tttturtle-russ requested changes
感觉改的太复杂了，逻辑保持返回university或None就行，没必要增加参数，python中None和False在if中效果应该是差不多的。

2024-10-24 13:41 UTC, tttturtle-russ commented
这样看来使用一个标志参数似乎是一个解决办法， @mudongliang @jxlpzqc 怎么看

2025-07-20 11:31 UTC, mudongliang commented
时间过长，没有active反馈，PR暂时关闭

2025-07-20 11:31 UTC, closed without merging